FanProject_Atlantis/models.py
import firebase_admin
import platform

from flask_babel import Babel
from flask_login import LoginManager
from firebase_admin import credentials
from firebase_admin import firestore


babel = Babel()
login_manager = LoginManager()
if platform.system().capitalize() == "Windows":
    path = r"etc\secrets\2034ca177738f5073c7668bd11dfcbcfd50146cb.json"
else:
    path = "/etc/secrets/credential.json"
cred = credentials.Certificate(path)
firebase_admin.initialize_app(cred)
firebase = firestore.client()

FanProject_Atlantis/__init__.py
from importlib import import_module

from flask import Flask
from flask import render_template
from flask import request

from . import config
from .context import inject_variables
from .context import date_fromisoformate
from .context import datetime_fromisoformate
from .models import babel
from .models import firebase
from .models import login_manager


def get_locale():
    return request.accept_languages.best_match(["zh", "en"])


def register_blueprints(app):
    """ Register every views.py file foreach app. """
    for blueprint in app.config["BLUEPRINTS"]:
        module = import_module(f"FanProject_Atlantis.apps.{blueprint}.views")
        app.register_blueprint(module.blueprint)


def create_app(testing=False):
    app = Flask(__name__)
    if testing:
        app.config.from_object(config.DevelopmentConfig())
    else:
        app.config.from_object(config.ProductionConfig())

    app.config["TEMPLATES_AUTO_RELOAD"] = True
    app.jinja_env.auto_reload = True

    app.context_processor(inject_variables)
    app.add_template_filter(date_fromisoformate)
    app.add_template_filter(datetime_fromisoformate)

    # Register error handlers
    app.errorhandler(404)(lambda e: (render_template("404.html"), 404))
    app.errorhandler(500)(lambda e: (render_template("500.html"), 500))

    babel.init_app(app, locale_selector=get_locale)
    login_manager.init_app(app)
    register_blueprints(app)
    return app

FanProject_Atlantis/apps/home/__init__.py
from flask import Blueprint


blueprint = Blueprint(
    "home", __name__,
    url_prefix="/",
    template_folder="templates",
    static_folder="static",
    static_url_path="home/static"
)

FanProject_Atlantis/apps/home/views.py
import random
from flask import flash
from flask import render_template
from flask import request
from . import blueprint


@blueprint.route("/")
@blueprint.route("/home")
def home():
    return render_template("home.html")


@blueprint.route("/about")
def about():
    return render_template("about.html")


@blueprint.route("/privacy-policy")
def privacy_policy():
    return render_template("privacy-policy.html")

POKER_RANKS = {0:"2", 1:"3", 2:"4", 3:"5", 4:"6", 5:"7", 6:"8", 7:"9", 8:"10", 9:"J", 10:"Q", 11:"K", 12:"A"}
POKER_SUITS = {0:"♣梅花", 1:"♦方塊", 2:"♥紅心", 3:"♠黑桃"}


@blueprint.route("/highcard", methods=["GET", "POST"])
def highcard():

    def get_card():
        value = random.sample(range(0, 51), k=1)[0]
        card = f"{POKER_SUITS.get(value % 4)}{POKER_RANKS.get(value // 4)}"
        return card, value

    first_card, first_card_value = get_card()

    if request.method == "POST":
        card = request.form.get("firstCard")
        card_value = int(request.form.get("firstCardValue"))
        guess = request.form.get("guess")
        second_card, second_card_value = get_card()

        match guess:
            case "大":
                win = True if second_card_value > card_value else False
            case "小":
                win = True if second_card_value < card_value else False

        if win:
            flash(f"你贏了，第二張牌是 {second_card}")
        else:
            flash(f"你輸了，第二張牌是 {second_card}")

    return render_template(
        "highcard.html",
        first_card=first_card,
        first_card_value=first_card_value,
    )

FanProject_Atlantis/apps/project/__init__.py
from flask import Blueprint


blueprint = Blueprint(
    "project", __name__,
    url_prefix="/project",
    template_folder="templates",
    static_folder="static",
    static_url_path="project/static"
)

FanProject_Atlantis/apps/project/views.py
from cachetools import cached
from cachetools import TTLCache
from firebase_admin import firestore
from flask import abort
from flask import render_template
from flask import url_for

from . import blueprint
from FanProject_Atlantis import firebase


@cached(cache=TTLCache(maxsize=8, ttl=3600))
def get_projects(limit=None, project_id=None) -> list:
    projects_ref = firebase.collection("projects")

    if project_id is None:
        docs = projects_ref.order_by("date_start", direction=firestore.Query.DESCENDING).limit(limit).get()
        projects = [doc.to_dict() for doc in docs]
        return projects

    project = projects_ref.document(project_id).get()
    if not project.exists:
        abort(404)

    return project.to_dict()


@blueprint.route("/api", methods=["GET"])
@blueprint.route("/api/<project_id>", methods=["GET"])
def project_api(project_id: str=None):
    if project_id is None:
        try:
            projects = get_projects(limit=5)
        except Exception as exce:
            # TODO: error handling
            print(exce)
            projects = None

        return render_template("recentProjects.html", projects=projects)


@blueprint.route("/")
@blueprint.route("/<project_id>")
def project_page(project_id: str=None):
    if project_id is None:
        try:
            projects = get_projects()
        except Exception as exce:
            # TODO: error handling
            print(exce)
            projects = None
        return render_template("projects.html", projects=projects)

    project = get_projects(project_id=project_id)
    return render_template(f"project.html", project=project)


@blueprint.route("/gawr-gura-birthday-2022")
def project_2022_bday():
    return render_template("2022bday.html")


@blueprint.route("/gawr-gura-birthday-2023")
def project_2023_bday():
    return render_template("2023bday.html")

FanProject_Atlantis/templates/base.html
<!DOCTYPE html>

<html lang="zh-TW" data-bs-theme="light">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block meta %}{% endblock meta %}
  <title>{% block title %}{% endblock title %} - {{ _("亞特蘭提斯企劃組") }}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/css/site.css" rel="stylesheet" />
  {% block stylesheets %}{% endblock stylesheets %}
</head>
<body class="base">
  {% include "includes/navbar.html" %}
  <div class="progress scrollProgressBar fixed-top">
    <div class="progress-bar" role="progressbar" id="scrollProgressBar"></div>
  </div>
  <main>
    {% block content %}{% endblock content %}
  </main>
  <footer class="container-fluid px-lg-5">
    <hr class="hr-edge-fade hr-with-content" data-content="🔱" />
    <div class="d-flex row mb-lg-0 mb-3">
      <div class="col-lg-auto col-12">
        <p class="me-auto">
          <span>© 2023 <i class="bi bi-discord pe-1" style="color: #7289D9;"></i>「🔱亞特蘭提斯🦈」</span>
        </p>
      </div>
      <div class="col-lg-auto justify-content-end ms-auto col-12">
        <a class="px-3" href="{{ url_for('home.privacy_policy') }}">{{ _("隱私權政策") }}</a>
        <a class="px-3 float-end" href="#"><i class="bi bi-chevron-bar-up"></i>TOP</a>
      </div>
    </div>
  </footer>
  {% include "includes/scripts.html" %}
  {% block scripts %}{% endblock scripts%}
</body>
</html>

FanProject_Atlantis/templates/base_home.html
<!DOCTYPE html>

<html lang="zh-TW">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block meta %}{% endblock meta %}
  <title>{% block title %}{% endblock title %}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  <link href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css" rel="stylesheet">
  <link href="/static/css/site.css" rel="stylesheet" />
  {% block stylesheets %}{% endblock stylesheets %}
</head>
<body>
  {% block header %}{% endblock header %}
  <main class="p-3">
    {% block content %}{% endblock content %}
  </main>
  <footer class="container-fluid px-lg-5">
    <hr class="hr-edge-fade hr-with-content" data-content="🔱" />
    <div class="d-flex row mb-lg-0 mb-3">
      <div class="col-lg-auto col-12">
        <p class="me-auto">
          <span>© 2023 <i class="bi bi-discord pe-1" style="color: #7289D9;"></i>「🔱亞特蘭提斯🦈」</span>
        </p>
      </div>
      <div class="col-lg-auto justify-content-end ms-auto col-12">
        <a class="px-3" href="{{ url_for('home.privacy_policy') }}">{{ _("隱私權政策") }}</a>
        <a class="px-3 float-end" href="#"><i class="bi bi-chevron-bar-up"></i>TOP</a>
      </div>
    </div>
  </footer>
  {% include "includes/scripts.html" %}
  {% block scripts %}{% endblock scripts%}
</body>
</html>

FanProject_Atlantis/templates/base_one_page.html
<!DOCTYPE html>

<html lang="zh-TW">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1">
  {% block meta %}{% endblock meta %}
  <title>{% block title %}{% endblock title %} - {{ _("亞特蘭提斯企劃組") }}</title>
  <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" />
  {% block stylesheets %}{% endblock stylesheets %}
</head>
<body class="d-flex vh-100 vw-100" style="background-color: #323232;" >
  <main class="d-flex m-auto">
    {% block content %}{% endblock content %}
  </main>
</body>
</html>

FanProject_Atlantis/templates/includes/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark fixed-top">
  <div class="container-fluid px-lg-5">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="navbar-nav">
      <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{url_for('home.home')}}">{{ _("亞特蘭提斯企劃組") }}</a></li>
    </ul>
    <button id="theme-toggle" class="btn me-0 light-switch" type="button">
      <i class="bi bi-sun-fill" id="theme-icon"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbar">
      <ul class="navbar-nav">
        <li class="nav-item px-3"><a class="strong-text hover-underline-animation" href="{{url_for('home.about')}}">About</a></li>
        <li class="nav-item px-3"><a class="strong-text hover-underline-animation" href="{{url_for('project.project_page')}}">Projects</a></li>
        <li class="nav-item px-3 dropdown">
          <a class="nav-link dropdown-toggle strong-text p-0" href="#" data-bs-toggle="dropdown">Projects(Legacy)</a>
          <ul class="dropdown-menu bg-dark">
            <li><a class="dropdown-item" href="{{url_for('project.project_2022_bday')}}"><span style="text-shadow: none;">{{ _("生日企劃") }} 2022</span></a></li>
            <li><a class="dropdown-item" href="{{url_for('project.project_2023_bday')}}"><span style="text-shadow: none;">{{ _("生日企劃") }} 2023</span></a></li>
          </ul>
        </li>
      </ul>
      <ul class="navbar-nav ms-auto px-lg-5">
        {% if current_user.is_authenticated %}
          <li class="nav-item px-3">
            <a class="stroke-light">Hi, {{ current_user.username }}</a>
          </li>
          <img class="navbar-avatar rounded-circle d-lg-block d-none" src='https://cdn.discordapp.com/avatars/{{ current_user.id }}/{{ current_user.avatar }}' alt='Discord Avatar' \>
          <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{ url_for('auth.logout') }}">{{ _("登出") }}</a></li>
        {% else %}
          <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{ url_for('auth.login') }}">{{ _("Discord 登入") }}</a></li>
        {% endif %}
      </ul>
    </div> <!-- div#navbar -->
  </div> <!-- div.container-fluid.px-lg-5 -->
</nav>

FanProject_Atlantis/templates/includes/scripts.html
<script type="module" src="/static/js/site.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
<script src="https://code.jquery.com/jquery-3.6.3.min.js"></script>