FanProject_Atlantis/apps/home/__init__.py
from flask import Blueprint


blueprint = Blueprint(
    "home", __name__,
    url_prefix="/",
    template_folder="templates",
    static_folder="static",
    static_url_path="home/static"
)

FanProject_Atlantis/apps/home/views.py
import random
from flask import flash
from flask import render_template
from flask import request
from . import blueprint


@blueprint.route("/")
@blueprint.route("/home")
def home():
    return render_template("home.html")


@blueprint.route("/about")
def about():
    return render_template("about.html")


@blueprint.route("/privacy-policy")
def privacy_policy():
    return render_template("privacy-policy.html")

POKER_RANKS = {0:"2", 1:"3", 2:"4", 3:"5", 4:"6", 5:"7", 6:"8", 7:"9", 8:"10", 9:"J", 10:"Q", 11:"K", 12:"A"}
POKER_SUITS = {0:"♣梅花", 1:"♦方塊", 2:"♥紅心", 3:"♠黑桃"}


@blueprint.route("/highcard", methods=["GET", "POST"])
def highcard():

    def get_card():
        value = random.sample(range(0, 51), k=1)[0]
        card = f"{POKER_SUITS.get(value % 4)}{POKER_RANKS.get(value // 4)}"
        return card, value

    first_card, first_card_value = get_card()

    if request.method == "POST":
        card = request.form.get("firstCard")
        card_value = int(request.form.get("firstCardValue"))
        guess = request.form.get("guess")
        second_card, second_card_value = get_card()

        match guess:
            case "大":
                win = True if second_card_value > card_value else False
            case "小":
                win = True if second_card_value < card_value else False

        if win:
            flash(f"你贏了，第二張牌是 {second_card}")
        else:
            flash(f"你輸了，第二張牌是 {second_card}")

    return render_template(
        "highcard.html",
        first_card=first_card,
        first_card_value=first_card_value,
    )

FanProject_Atlantis/apps/home/templates/about.html
{% extends "base.html" %}

{% block title %}{{ _("關於我們") }}{% endblock title %}

{% block meta %}
<meta property="og:title" content="關於我們 - 亞特蘭提斯企劃組">
<meta property="og:description" content="亞特蘭提斯企劃組...亞特蘭提斯企劃組是由 Gawr Gura 粉絲 Discord 群組「🔱亞特蘭提斯🦈」組成的活動企劃組，主要為 Hololive English -Myth- 旗下藝人 Gawr Gura 舉辦各式各樣的推廣活動，所有活動皆為粉絲自發性活動，並無營利性質。">
{% endblock meta %}

{% block stylesheets %}
{% endblock stylesheets %}

{% block content %}
<div id="aboutCarousel" class="carousel slide" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#aboutCarousel" data-bs-slide-to="0" class="active" aria-current="true"></button>
    <button type="button" data-bs-target="#aboutCarousel" data-bs-slide-to="1"></button>
    <button type="button" data-bs-target="#aboutCarousel" data-bs-slide-to="2"></button>
    <button type="button" data-bs-target="#aboutCarousel" data-bs-slide-to="3"></button>
    <button type="button" data-bs-target="#aboutCarousel" data-bs-slide-to="4"></button>
    <button type="button" data-bs-target="#aboutCarousel" data-bs-slide-to="5"></button>
  </div>

  <div class="carousel-inner">
    <div class="carousel-item active">
      <img src="{{url_for('project.static', filename='img/2022/ee9e2a9f65ba49dd405c735e8c2bafaeb55d3e49.webp')}}" loading="lazy" />
      <div class="container">
        <div class="carousel-caption text-start">
          <span class="h5 stroke-dark">{{ _("2022 Gawr Gura 生日公車活動") }}</span><br />
          <span class="h1 stroke-dark">{{ _("高雄") }} 90 {{ _("車門側") }}</span><br />
          <div class="d-flex align-items-center">
            <img class="rounded-circle" src="https://pbs.twimg.com/profile_images/1333212491841630212/w3CagKjb_400x400.jpg" style="height: 5em; width: 5em;" loading="lazy" focusable="false" />
            <span class="p-3 stroke-dark h5">
              {{ _("繪師") }}：鯊魚咬尾巴<br />
              <a class="bi bi-twitter stroke-light" href="https://twitter.com/SharkBiteTail" target="_blank" style="color: #1DA1F2;"></a>
            </span>
          </div>
        </div>
      </div>
    </div> <!-- div.carousel-item -->
    <div class="carousel-item">
      <img src="{{url_for('project.static', filename='img/2022/5f7bca1ea8f6950c1a2d4d674d2871fdb5ba8741.webp')}}" style="object-position: 35% 60%;" loading="lazy" />
      <div class="container">
        <div class="carousel-caption text-start">
          <span class="h5 stroke-dark">{{ _("2022 Gawr Gura 生日公車活動") }}</span><br />
          <span class="h1 stroke-dark">{{ _("高雄") }} 90 {{ _("司機側") }}</span><br />
          <div class="d-flex align-items-center">
            <svg class="rounded-circle" role="img" style="height: 5em; width: 5em;" focusable="false"><rect width="100%" height="100%" fill="#5CB8E4" /></svg>
            <span class="p-3 stroke-dark h5">
              {{ _("繪師") }}：たま・TAMA<br />
            </span>
          </div>
        </div>
      </div>
    </div> <!-- div.carousel-item -->
    <div class="carousel-item">
      <img src="{{url_for('project.static', filename='img/2022/8b3ca6b46667571b2ff406c4391cfec25f7c635d.webp')}}" style="object-position: 50% 60%;" loading="lazy" />
      <div class="container">
        <div class="carousel-caption text-start">
          <span class="h5 stroke-dark">{{ _("2022 Gawr Gura 生日公車活動") }}</span><br />
          <span class="h1 stroke-dark">{{ _("台中") }} 33 {{ _("車門側") }}</span><br />
          <div class="d-flex align-items-center">
            <svg class="rounded-circle" role="img" style="height: 5em; width: 5em;" focusable="false"><rect width="100%" height="100%" fill="#5CB8E4" /></svg>
            <span class="p-3 stroke-dark h5">
              {{ _("繪師") }}：たま・TAMA<br />
            </span>
          </div>
        </div>
      </div>
    </div> <!-- div.carousel-item -->
    <div class="carousel-item">
      <img src="{{url_for('project.static', filename='img/2022/955b05173dfee4a449e4c1c260bf73ef2b9d7c15.webp')}}" style="object-position: 50% 60%;" loading="lazy" />
      <div class="container">
        <div class="carousel-caption text-start">
          <span class="h5 stroke-dark">{{ _("2022 Gawr Gura 生日公車活動") }}</span><br />
          <span class="h1 stroke-dark">{{ _("高雄") }} 90 {{ _("車門側") }}</span><br />
          <div class="d-flex align-items-center">
            <img class="rounded-circle" src="https://pbs.twimg.com/profile_images/1609034921225650177/88oav8eN_400x400.jpg" style="height: 5em; width: 5em;" loading="lazy" focusable="false" />
            <span class="p-3 stroke-dark h5">
              {{ _("繪師") }}：00魚<br />
              <a class="bi bi-twitter stroke-light" href="https://twitter.com/lydia601303041" target="_blank" style="color: #1DA1F2;"></a>
            </span>
          </div>
        </div>
      </div>
    </div> <!-- div.carousel-item -->
    <div class="carousel-item">
      <img src="{{url_for('project.static', filename='img/2022/f72c8b76d36d8d0ac4e7fa0ba13cbf24b35aaab1.webp')}}" style="object-position: 40% 60%;" loading="lazy" />
      <div class="container">
        <div class="carousel-caption text-start">
          <span class="h5 stroke-dark">{{ _("2022 Gawr Gura 生日公車活動") }}</span><br />
          <span class="h1 stroke-dark">{{ _("台中") }} 35 {{ _("司機側") }}</span><br />
          <div class="d-flex align-items-center">
            <img class="rounded-circle" src="https://pbs.twimg.com/profile_images/1609034921225650177/88oav8eN_400x400.jpg" style="height: 5em; width: 5em;" focusable="false" loading="lazy" />
            <span class="p-3 stroke-dark h5">
              {{ _("繪師") }}：00魚<br />
              <a class="bi bi-twitter stroke-light" href="https://twitter.com/lydia601303041" target="_blank" style="color: #1DA1F2;"></a>
            </span>
          </div>
        </div>
      </div>
    </div> <!-- div.carousel-item -->
    <div class="carousel-item">
      <img src="{{url_for('project.static', filename='img/2022/19b0e1c010646c2ed6c0339aec6ee42a1e64d701.webp')}}" style="object-position: 55% 55%;" loading="lazy" />
      <div class="container">
        <div class="carousel-caption text-start">
          <span class="h5 stroke-dark">{{ _("2022 Gawr Gura 生日公車活動") }}</span><br />
          <span class="h1 stroke-dark">{{ _("台中") }} 35 {{ _("車門側") }}</span><br />
          <div class="d-flex align-items-center">
            <img class="rounded-circle" src="https://pbs.twimg.com/profile_images/1623190901416939523/QzbhH4Ng_400x400.jpg" style="height: 5em; width: 5em;" loading="lazy" focusable="false" />
            <span class="p-3 stroke-dark h5">
              {{ _("繪師") }}：hirotaka<br />
              <a class="bi bi-twitter stroke-light" href="https://twitter.com/hirotaka0125" target="_blank" style="color: #1DA1F2;"></a>
            </span>
          </div>
        </div>
      </div>
    </div> <!-- div.carousel-item -->
  </div> <!-- div.carousel-inner -->

  <button class="carousel-control-prev" type="button" data-bs-target="#aboutCarousel" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#aboutCarousel" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div> <!-- #aboutCarousel.arousel .slide -->

<div class="container pt-5">
  <div class="row">
    <div class="col-lg-8 mb-3">
      <h2 class="featurette-header fw-normal lh-1 mb-3"><i class="bi bi-patch-question-fill me-1 d-lg-none d-inline"></i>{{ _("我們是誰？") }}</h2>
      <p>
        {{ _("起初，我們只是跟普通粉絲們一樣喜歡著鯊鯊，直到我們見到了第一次的海外粉絲們籌劃的生日慶祝活動，甚至看到了鯊鯊的感動與淚水，這時我們才意識到：「如果海外粉絲能做到，我們也能做到。」我們的目標是要讓鯊鯊知道有這麼一群人支持著她，並與她一起創造種種回憶。") }}
      </p>
      <p>
        {{ _("當然，企劃的推動總要有人付諸行動，我們在 Gura 的第二次生日上踏出了第一步。當時，我們對這些事情還是一知半解，但我們還是成功地完成了公車廣告的慶祝企劃，也讓鯊鯊看見了我們粉絲們的努力成果。即使第一次籌劃中有許多不足之處，但我們願意虛心學習並繼續付出，往後的活動企畫也請各位多多指教和協助。") }}
      </p>
    </div>
    <div class="col-lg-4 d-lg-block d-none text-center" style="font-size: 10em; color: var(--theme-secondary); ">
      <i class="bi bi-patch-question-fill"></i>
    </div>
    <div class="col-lg-4 d-lg-block d-none text-center" style="font-size: 10em; color: var(--theme-secondary); ">
      <i class="bi bi-balloon-heart"></i>
    </div>
    <div class="col-lg-8 mb-3 ms-lg-auto">
      <h2 class="featurette-header fw-normal lh-1 mb-3"><i class="bi bi-balloon-heart me-1 d-lg-none d-inline"></i>{{ _("主辦企劃") }}</h2>
      <div id="recentProjects">
        <div class="spinner spinner-border m-5" role="status">
          <span class="visually-hidden">Loading...</span>
        </div>
      </div>
    </div>
  </div> <!-- div.row -->

  <hr class="hr-edge-fade" />

  <div class="row text-center mt-5">
    <h1>{{ _("企劃組核心成員") }}</h1>
  </div>
  <div class="row">
    <div class="col-lg-4 text-center pt-5">
      <img class="rounded-circle" src="https://cdn.discordapp.com/avatars/407063351072653313/a_f541e1243a91a599414a4bdcb7c16f83.gif" loading="lazy" focusable="false" />
      <h2 class="fw-normal">{{ _("企劃主辦人") }}</h2>
      <i class="bi bi-discord" style="color: #7289D9;">サメ#4015</i>
    </div> <!-- div.col-lg-4 -->
    <div class="col-lg-4 text-center pt-5">
      <img class="rounded-circle" src="https://cdn.discordapp.com/avatars/387573599919276032/a_c69aac81a341b581e97af8c68258f958.gif" loading="lazy" focusable="false" />
      <h2 class="fw-normal">{{ _("主辦 Discord 群群主") }}</h2>
      <i class="bi bi-discord" style="color: #7289D9;">林昕渪#1202</i>
    </div> <!-- div.col-lg-4 -->
    <div class="col-lg-4 text-center pt-5">
      <img class="rounded-circle" src="https://cdn.discordapp.com/avatars/443018500345430016/3a326eede9ac599e5e9fd3af54908163.webp" loading="lazy" focusable="false" />
      <h2 class="fw-normal">{{ _("主辦 Discord 群管理員") }}</h2>
      <i class="bi bi-discord" style="color: #7289D9;">vic2013614#3905</i>
    </div> <!-- div.col-lg-4 -->
  </div> <!-- div.row -->
</div><!-- div.container .pt-5 -->
{% endblock content %}

{% block scripts %}
<script>
  $(function () {
    $.ajax("{{ url_for('project.project_api') }}")
      .done(function (data) {
        $("#recentProjects").html(data)
      })
      .fail(function (jqXHR, textStatus, errorThrown) {
        console.log(errorThrown)
      })
  })
</script>
{% endblock scripts%}

FanProject_Atlantis/apps/home/templates/highcard.html
{% extends "base_one_page.html" %}

{% block content %}
<div class="modal" id="resultModal" tabindex="-1">
  <div class="modal-dialog modal-dialog-centered">
    <div class="modal-content">
      <div class="modal-body" id="modalBody">
        <!--MODAL MESSAGE-->
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">好</button>
      </div>
    </div>
  </div>
</div>

<div class="contain-fluid">
  <form method="POST">
    <span>
      第一張牌為
      <input class="form-control-plaintext" name="firstCard" value="{{first_card}}" readonly />
      <input class="form-control-plaintext" name="firstCardValue" value="{{first_card_value}}" hidden />
    </span><br />
    <input class="btn btn-primary" type="submit" name="guess" value="大" />
    <input class="btn btn-primary" type="submit" name="guess" value="小" />
  </form>
  <hr>
  <div class="pt-3">
    <a class="btn btn-primary" href="{{url_for('home.home')}}">玩膩了，回首頁</a>
  </div>
</div>
{% endblock content %}

{% block scripts %}
{% with messages = get_flashed_messages() %}
{% if messages %}
{% for message in messages %}
<script>
  $("#modalBody").text("{{message}}")
  new bootstrap.Modal($('#resultModal')).show();
</script>
{% endfor %}
{% endif %}
{% endwith %}
{% endblock scripts %}

FanProject_Atlantis/apps/home/templates/home.html
{% extends "base_home.html" %}

{% block title %}{{ _("亞特蘭提斯企劃組") }}{% endblock title %}

{% block meta %}
<meta property="og:title" content="亞特蘭提斯企劃組">
<meta property="og:description" content="亞特蘭提斯企劃組...亞特蘭提斯企劃組是由 Gawr Gura 粉絲 Discord 群組「🔱亞特蘭提斯🦈」組成的活動企劃組，主要為 Hololive English -Myth- 旗下藝人 Gawr Gura 舉辦各式各樣的推廣活動，所有活動皆為粉絲自發性活動，並無營利性質。">
{% endblock meta %}

{% block stylesheets %}
<link href="{{url_for('home.static', filename='css/home.css')}}" rel="stylesheet" />
{% endblock stylesheets %}

{% block header %}
<header class="intro">
  <nav class="navbar navbar-expand-lg navbar-transparent fixed-top">
    <div class="container-fluid d-flex px-lg-5">
      <button class="navbar-toggler navbar-dark" type="button" data-bs-toggle="collapse" data-bs-target="#navbar">
        <span class="navbar-toggler-icon"></span>
      </button>
      <ul class="navbar-nav">
        <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{url_for('home.home')}}">{{ _("亞特蘭提斯企劃組") }}</a></li>
      </ul>
      <button id="theme-toggle" class="btn me-0 light-switch" type="button">
        <i class="bi bi-sun-fill" id="theme-icon"></i>
      </button>
      <div class="collapse navbar-collapse" id="navbar">
        <ul class="navbar-nav">
          <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{url_for('home.about')}}">About</a></li>
          <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{url_for('project.project_page')}}">Projects</a></li>
          <li class="nav-item px-3 dropdown">
            <a class="nav-link stroke-light dropdown-toggle p-0" href="#" data-bs-toggle="dropdown">Projects(Legacy)</a>
            <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="{{url_for('project.project_2022_bday')}}"><span style="text-shadow: none;">{{ _("生日企劃") }} 2022</span></a></li>
              <li><a class="dropdown-item" href="{{url_for('project.project_2023_bday')}}"><span style="text-shadow: none;">{{ _("生日企劃") }} 2023</span></a></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav ms-auto px-lg-5">
          {% if current_user.is_authenticated %}
          <li class="nav-item px-3">
            <a class="stroke-light">Hi, {{ current_user.username }}</a>
          </li>
          <img class="navbar-avatar rounded-circle d-lg-block d-none" src='https://cdn.discordapp.com/avatars/{{ current_user.id }}/{{ current_user.avatar }}' alt='Discord Avatar' \>
          <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{ url_for('auth.logout') }}">{{ _("登出") }}</a></li>
          {% else %}
          <li class="nav-item px-3"><a class="stroke-light hover-underline-animation" href="{{ url_for('auth.login') }}">{{ _("Discord 登入") }}</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  <div class="title">
    <span>Gawr Gura 2023<br>{{ _("生日企劃") }}</span>
  </div>
  <img src="{{url_for('home.static', filename='img/0bb2693a5ec2b794dccd48882c87d2e93e09301d.webp')}}" />
</header>
{% endblock header %}

{% block content %}
<div class="container">
  <p>
    這裡會是 Gawr Gura 生日企劃網站，如果我有時間做的話。<br />
    下面提供個小遊戲怕你無聊。
  </p>
  <a class="btn btn-primary" href="{{url_for('home.highcard')}}">PLAY</a>
</div>
{% endblock content %}

{% block scripts %}
<script>
  $(window).on('scroll', function () {
    if ($(window).scrollTop()) {
      $('nav').addClass('dark')
    } else {
      $('nav').removeClass('dark')
    }
  })
</script>
{% endblock scripts %}

FanProject_Atlantis/apps/home/templates/privacy-policy.html
{% extends "base.html" %}

{% block title %}{{ _("隱私權政策") }}{% endblock title %}

{% block meta %}
<meta property="og:title" content="隱私權政策">
<meta property="og:description" content="亞特蘭提斯企劃組網站之隱私權政策">
{% endblock meta %}

{% block stylesheets %}
<link href="/static/css/timeline.css" rel="stylesheet" />
<link href="{{url_for('project.static', filename='css/project.css')}}" rel="stylesheet" />
{% endblock stylesheets %}

{% block content %}
<div class="container-lg container-fluid pt-4">
  <h1>{{ _("隱私權政策") }}</h1>
  <h3>{{ _("隱私權政策適用範圍") }}</h3>
  <ul>
    <li><p>{{ _("隱私權保護政策內容，適用於以「fanproject-atlantis.com」網域為原則之網站（以下稱本網站）。不適用於經由本網站以外的相關連結網站，也不適用於非本網站所委託或參與管理的人員。") }}</p></li>
  </ul>
  <h3>{{ _("資料蒐集、處理及利用方式") }}</h3>
  <ul>
    <li><p>{{ _("一般瀏覽之情況：本網站會自動產生相關瀏覽紀錄，包含連線設備 IP 地址、使用時間、使用的瀏覽器及請求的資源。") }}</p></li>
    <li><p>{{ _("主動以 Discord 登入之情況：本網站使用 Disocrd OAuth 2.0 API 驗證 Disocrd 帳號，本網站僅記錄使用者 UID、使用者名稱、頭像作為登入資訊儲存，此登入資訊將於登出網站時自動清除，本網站不會、也不能儲存您在 Disocrd 上的密碼。") }}</p></li>
    <li><p>{{ _("主動使用本網站留言等功能之情況：本網站會將使用者 UID、使用者名稱、頭像基本資訊儲存至資料庫。") }}</p></li>
    <li><p>{{ _("活動所需提供個人實名資料之情況：本網站將不會紀錄完整個人資料，資料存入時將自動刪除部分資訊，因活動金流或其他需求會將部分實名資料展示於本網站上，如匯款帳號末五碼及姓名首字等。") }}</p></li>
  </ul>
  <h3>{{ _("資料保護") }}</h3>
  <ul>
    <li><p>{{ _("本網站之資料僅能由網站管理員及亞特蘭提斯企劃組管理方存取，絕對不會提供、交換、出租或販售至第三方使用。") }}</p></li>
  </ul>
  <h3>{{ _("Cookie 使用") }}</h3>
  <ul>
    <li><p>{{ _("為了提供您最佳的服務，本網站會在您的電腦中放置並取用我們的 Cookie，若您不願接受 Cookie 的寫入，您可在您使用的瀏覽器功能項中設定隱私權等級為高，即可拒絕 Cookie 的寫入，但可能會導致網站某些功能無法正常執行。") }}</p></li>
  </ul>
  <h3>{{ _("隱私權政策修正") }}</h3>
  <ul>
    <li><p>{{ _("本網站隱私權保護政策將因應需求隨時進行修正。") }}</p></li>
  </ul>
</div> <!-- div.contanier -->
{% endblock content %}